apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vsnet-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: vsnet-auth
    spec:
      nodeSelector:
        role: apps
      containers:
      - name: vsnet-auth
        image: makeshiftsoftware/vsnet-auth:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        env:
          - name: NODE_ENV
            value: "development"
          - name: PORT
            value: "3000"
          - name: LOG_LEVEL
            value: "debug"
          - name: HTTP_LOG_LEVEL
            value: "dev"
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: app_secret
          - name: DB_NAME
            value: "makeshift"
          - name: DB_USER
            value: "makeshift"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: db_password